name: Obtain SSL certs

# Controls when the workflow will run.
on:
  # Triggers the workflow on a timer. This particular timer runs on the first day of the month. 
  # CertBot certs are renewable every 30 days, so this should work for that purpose.
  schedule:
    - cron:  '0 0 1 * *'
  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
jobs:
  obtain:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        domains: ["*.hieupth.xyz", "*.hieupth.me"]
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Obtain certs
        run: |
          docker run -v ./certs:/certs \
              -e DOMAINS=${{ matrix.domains }} \
              -e EMAIL=${{ secrets.EMAIL }} \
              -e CLOUDFLARE_TOKEN=${{ secrets.CLOUDFLARE_TOKEN }} \
              -e ENCRYPT_PASS=${{ secrets.ENCRYPT_PASS }} \
            hieupth/certbot
      -
        name: Commit and push
        run: |
          sudo chmod -R 777 ./certs
          git config --global user.name "hieupth"
          git config --global user.email "64821726+hieupth@users.noreply.github.com"    
          git add -A
          git commit -m "chore: obtain certs"
          git push