name: Build fetch

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - images/gitfetch/*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build image
        uses: docker/build-push-action@v3
        with:
          push: true
          context: images/gitfetch
          platforms: linux/amd64,linux/arm64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/certbot:gitfetch
  trigger:
    needs: build
    runs-on: ubuntu-latest
    steps:
      -
        name: FRP
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GHA_WORKFLOW_TOKEN }}
          script: |
            const result = await github.rest.actions.createWorkflowDispatch({
              owner: 'hieupth',
              repo: 'frp',
              workflow_id: 'build.yml',
              ref: 'main'
            })
            console.log(result)
