name: Update description

on:
  push:
    branches:
      - 'main'
    paths:
      - README.md
  workflow_run:
    workflows: ["Build base images", "Build encryption images", "Build decryption images"]
    types:
      - completed
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - 
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Update docker description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: hieupth/certbot